obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]] 
robot_radius: 1.0 
inflation_radius: 0.55

observation_sources: base_scan

base_scan: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /base_scan, marking: true, clearing: true}
